# coding: utf-8

"""
    Stream Video API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v79.45.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from model import schemas  # noqa: F401


class RingSettingsRequest(schemas.DictSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    class MetaOapg:
        class properties:
            auto_cancel_timeout_ms = schemas.Int32Schema
            auto_reject_timeout_ms = schemas.Int32Schema
            __annotations__ = {
                "auto_cancel_timeout_ms": auto_cancel_timeout_ms,
                "auto_reject_timeout_ms": auto_reject_timeout_ms,
            }

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["auto_cancel_timeout_ms"]
    ) -> MetaOapg.properties.auto_cancel_timeout_ms:
        ...

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["auto_reject_timeout_ms"]
    ) -> MetaOapg.properties.auto_reject_timeout_ms:
        ...

    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema:
        ...

    def __getitem__(
        self,
        name: typing.Union[
            typing_extensions.Literal[
                "auto_cancel_timeout_ms",
                "auto_reject_timeout_ms",
            ],
            str,
        ],
    ):
        # dict_instance[name] accessor
        return super().__getitem__(name)

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["auto_cancel_timeout_ms"]
    ) -> typing.Union[MetaOapg.properties.auto_cancel_timeout_ms, schemas.Unset]:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["auto_reject_timeout_ms"]
    ) -> typing.Union[MetaOapg.properties.auto_reject_timeout_ms, schemas.Unset]:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: str
    ) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]:
        ...

    def get_item_oapg(
        self,
        name: typing.Union[
            typing_extensions.Literal[
                "auto_cancel_timeout_ms",
                "auto_reject_timeout_ms",
            ],
            str,
        ],
    ):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[
            dict,
            frozendict.frozendict,
        ],
        auto_cancel_timeout_ms: typing.Union[
            MetaOapg.properties.auto_cancel_timeout_ms,
            decimal.Decimal,
            int,
            schemas.Unset,
        ] = schemas.unset,
        auto_reject_timeout_ms: typing.Union[
            MetaOapg.properties.auto_reject_timeout_ms,
            decimal.Decimal,
            int,
            schemas.Unset,
        ] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[
            schemas.AnyTypeSchema,
            dict,
            frozendict.frozendict,
            str,
            date,
            datetime,
            uuid.UUID,
            int,
            float,
            decimal.Decimal,
            None,
            list,
            tuple,
            bytes,
        ],
    ) -> "RingSettingsRequest":
        return super().__new__(
            cls,
            *_args,
            auto_cancel_timeout_ms=auto_cancel_timeout_ms,
            auto_reject_timeout_ms=auto_reject_timeout_ms,
            _configuration=_configuration,
            **kwargs,
        )
