changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
      - github-actions
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Changes
      labels:
        - "*"
