import logging
from enum import Enum
from typing import Awaitable

import numpy as np
import numpy.typing as npt

__version__: str

def configure_logging(
    logger: logging.Logger | None, level: int, third_party_level: int = 30
) -> None:
    """Send SDK records at `level` or above, and records of third-party Rust
    crates at the less verbose of `level` and `third_party_level`, to `logger`
    and the loggers below it. `logger=None` stops forwarding. Process-wide: the
    last call wins. Returns after the records queued before the call have been
    delivered."""

class CallingState(Enum):
    IDLE = ...
    JOINING = ...
    JOINED = ...
    RECONNECTING = ...
    MIGRATING = ...
    RECONNECTING_FAILED = ...
    LEFT = ...

class TrackType(Enum):
    UNSPECIFIED = ...
    AUDIO = ...
    VIDEO = ...
    SCREEN_SHARE = ...
    SCREEN_SHARE_AUDIO = ...

class RemoteParticipant:
    @property
    def user_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def image(self) -> str: ...
    @property
    def roles(self) -> list[str]: ...
    @property
    def published_tracks(self) -> list[TrackType]: ...

class CallStateSnapshot:
    @property
    def participants(self) -> list[RemoteParticipant]: ...
    @property
    def own_capabilities(self) -> list[str]: ...

class ParticipantJoined:
    @property
    def participant(self) -> RemoteParticipant: ...

class ParticipantLeft:
    @property
    def participant(self) -> RemoteParticipant: ...

class TrackPublished:
    @property
    def user_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def track_type(self) -> TrackType: ...

class TrackUnpublished:
    @property
    def user_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def track_type(self) -> TrackType: ...

class CallEnded: ...

class CallingStateChanged:
    @property
    def state(self) -> CallingState: ...

Event = (
    ParticipantJoined
    | ParticipantLeft
    | TrackPublished
    | TrackUnpublished
    | CallEnded
    | CallingStateChanged
)

class EventStream:
    """Ends after `CallEnded` or `CallingStateChanged(LEFT)`, or at once if the
    call had already ended when the stream was created."""

    def __aiter__(self) -> EventStream: ...
    def __anext__(self) -> Awaitable[Event]: ...

class PcmFrame:
    @property
    def samples(self) -> npt.NDArray[np.int16]: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channels(self) -> int: ...

class VideoFrame:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def data(self) -> npt.NDArray[np.uint8]: ...
    @property
    def rtp_timestamp(self) -> int: ...

class RemoteTrack:
    @property
    def participant(self) -> RemoteParticipant: ...
    @property
    def track_type(self) -> TrackType: ...
    def next_pcm(self) -> Awaitable[PcmFrame | None]: ...
    def next_video_frame(self) -> Awaitable[VideoFrame | None]: ...

class TrackStream:
    """All streams of one call share one queue. Ends when the call ends, or at
    once if the call had already ended when the stream was created."""

    def __aiter__(self) -> TrackStream: ...
    def __anext__(self) -> Awaitable[RemoteTrack]: ...

class LocalAudioTrack:
    def __init__(self, pcm_queue_capacity: float | None = None) -> None:
        """``pcm_queue_capacity``: the seconds of PCM that ``write_pcm`` queues
        (``None``: the SDK default, 60 s). A write above it drops the oldest
        samples and raises ``PcmQueueOverflowError``."""
    def write_pcm(
        self, samples: npt.NDArray[np.int16], sample_rate: int, channels: int
    ) -> Awaitable[None]:
        """Await each write before the next; writes that run at the same time
        can reach the SDK out of order."""
    def flush(self) -> None: ...

class LocalVideoTrack:
    @staticmethod
    def vp8() -> LocalVideoTrack: ...
    @staticmethod
    def vp9() -> LocalVideoTrack: ...
    @staticmethod
    def h264() -> LocalVideoTrack: ...
    def write_i420(
        self, data: npt.NDArray[np.uint8], width: int, height: int, duration: float
    ) -> Awaitable[None]:
        """Await each write before the next; writes that run at the same time
        can reach the SDK out of order."""

class Call:
    def join(self, user_id: str, create: bool = True) -> Awaitable[None]: ...
    def leave(self) -> Awaitable[None]: ...
    def session_id(self) -> Awaitable[str | None]: ...
    @property
    def calling_state(self) -> CallingState: ...
    def participants(self) -> list[RemoteParticipant]: ...
    def call_state(self) -> CallStateSnapshot: ...
    def events(self) -> EventStream: ...
    def tracks(self) -> TrackStream: ...
    def publish_audio(self, track: LocalAudioTrack) -> Awaitable[None]: ...
    def publish_video(self, track: LocalVideoTrack) -> Awaitable[None]: ...
    def publish_screen_share(self, track: LocalVideoTrack) -> Awaitable[None]:
        """The SFU accepts VP8 for screen share (``LocalVideoTrack.vp8()``)."""
    def stop_publish_audio(self, track: LocalAudioTrack) -> Awaitable[None]:
        """Stops the track: later writes raise ``IllegalStateError``. A track
        that is not published is ignored."""
    def stop_publish_video(self, track: LocalVideoTrack) -> Awaitable[None]:
        """Stops the track: later writes raise ``IllegalStateError``. A track
        that is not published is ignored."""
    def stop_publish_screen_share(self, track: LocalVideoTrack) -> Awaitable[None]:
        """Stops the track: later writes raise ``IllegalStateError``. A track
        that is not published is ignored."""
    def update_subscriptions(
        self,
        audio: bool = True,
        video: bool = False,
        screen_share: bool = False,
        video_dimension: tuple[int, int] | None = None,
    ) -> Awaitable[None]: ...

class Client:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        base_url: str | None = None,
        ws_url: str | None = None,
        log_bodies: bool = False,
    ) -> None: ...
    def call(self, call_type: str, call_id: str) -> Call: ...
