# Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.
from getstream.models import *
from getstream.stream_response import StreamResponse


class Feed:
    def __init__(self, client, feed_group: str, feed_id: str, custom_data: Dict = None):
        self.id = feed_id
        self.feed_group = feed_group
        self.client = client
        self.custom_data = custom_data or {}

    def _sync_from_response(self, data):
        if hasattr(data, "feed") and isinstance(data.feed, FeedResponse):
            self.custom_data = data.feed.custom

    def delete(
        self,
        hard_delete: Optional[bool] = None,
        purge_user_activities: Optional[bool] = None,
    ) -> StreamResponse[DeleteFeedResponse]:
        response = self.client.delete_feed(
            feed_group_id=self.feed_group,
            feed_id=self.id,
            hard_delete=hard_delete,
            purge_user_activities=purge_user_activities,
        )
        self._sync_from_response(response.data)
        return response

    def get_or_create(
        self,
        id_around: Optional[str] = None,
        limit: Optional[int] = None,
        next: Optional[str] = None,
        prev: Optional[str] = None,
        user_id: Optional[str] = None,
        view: Optional[str] = None,
        watch: Optional[bool] = None,
        data: Optional[FeedInput] = None,
        enrichment_options: Optional[EnrichmentOptions] = None,
        external_ranking: Optional[Dict[str, object]] = None,
        filter: Optional[Dict[str, object]] = None,
        followers_pagination: Optional[PagerRequest] = None,
        following_pagination: Optional[PagerRequest] = None,
        friend_reactions_options: Optional[FriendReactionsOptions] = None,
        interest_weights: Optional[Dict[str, float]] = None,
        member_pagination: Optional[PagerRequest] = None,
        user: Optional[UserRequest] = None,
    ) -> StreamResponse[GetOrCreateFeedResponse]:
        response = self.client.get_or_create_feed(
            feed_group_id=self.feed_group,
            feed_id=self.id,
            id_around=id_around,
            limit=limit,
            next=next,
            prev=prev,
            user_id=user_id,
            view=view,
            watch=watch,
            data=data,
            enrichment_options=enrichment_options,
            external_ranking=external_ranking,
            filter=filter,
            followers_pagination=followers_pagination,
            following_pagination=following_pagination,
            friend_reactions_options=friend_reactions_options,
            interest_weights=interest_weights,
            member_pagination=member_pagination,
            user=user,
        )
        self._sync_from_response(response.data)
        return response

    def update(
        self,
        clear_location: Optional[bool] = None,
        created_by_id: Optional[str] = None,
        description: Optional[str] = None,
        enrich_own_fields: Optional[bool] = None,
        name: Optional[str] = None,
        filter_tags: Optional[List[str]] = None,
        custom: Optional[Dict[str, object]] = None,
        location: Optional[Location] = None,
    ) -> StreamResponse[UpdateFeedResponse]:
        response = self.client.update_feed(
            feed_group_id=self.feed_group,
            feed_id=self.id,
            clear_location=clear_location,
            created_by_id=created_by_id,
            description=description,
            enrich_own_fields=enrich_own_fields,
            name=name,
            filter_tags=filter_tags,
            custom=custom,
            location=location,
        )
        self._sync_from_response(response.data)
        return response

    def mark_activity(
        self,
        mark_all_read: Optional[bool] = None,
        mark_all_seen: Optional[bool] = None,
        user_id: Optional[str] = None,
        mark_read: Optional[List[str]] = None,
        mark_seen: Optional[List[str]] = None,
        mark_watched: Optional[List[str]] = None,
        user: Optional[UserRequest] = None,
    ) -> StreamResponse[Response]:
        response = self.client.mark_activity(
            feed_group_id=self.feed_group,
            feed_id=self.id,
            mark_all_read=mark_all_read,
            mark_all_seen=mark_all_seen,
            user_id=user_id,
            mark_read=mark_read,
            mark_seen=mark_seen,
            mark_watched=mark_watched,
            user=user,
        )
        self._sync_from_response(response.data)
        return response

    def unpin_activity(
        self,
        activity_id: str,
        enrich_own_fields: Optional[bool] = None,
        user_id: Optional[str] = None,
    ) -> StreamResponse[UnpinActivityResponse]:
        response = self.client.unpin_activity(
            feed_group_id=self.feed_group,
            feed_id=self.id,
            activity_id=activity_id,
            enrich_own_fields=enrich_own_fields,
            user_id=user_id,
        )
        self._sync_from_response(response.data)
        return response

    def pin_activity(
        self,
        activity_id: str,
        enrich_own_fields: Optional[bool] = None,
        user_id: Optional[str] = None,
        user: Optional[UserRequest] = None,
    ) -> StreamResponse[PinActivityResponse]:
        response = self.client.pin_activity(
            feed_group_id=self.feed_group,
            feed_id=self.id,
            activity_id=activity_id,
            enrich_own_fields=enrich_own_fields,
            user_id=user_id,
            user=user,
        )
        self._sync_from_response(response.data)
        return response

    def change_feed_visibility(
        self, visibility: str, pending_follows_action: Optional[str] = None
    ) -> StreamResponse[ChangeFeedVisibilityResponse]:
        response = self.client.change_feed_visibility(
            feed_group_id=self.feed_group,
            feed_id=self.id,
            visibility=visibility,
            pending_follows_action=pending_follows_action,
        )
        self._sync_from_response(response.data)
        return response

    def update_feed_members(
        self,
        operation: str,
        limit: Optional[int] = None,
        next: Optional[str] = None,
        prev: Optional[str] = None,
        members: Optional[List[FeedMemberRequest]] = None,
    ) -> StreamResponse[UpdateFeedMembersResponse]:
        response = self.client.update_feed_members(
            feed_group_id=self.feed_group,
            feed_id=self.id,
            operation=operation,
            limit=limit,
            next=next,
            prev=prev,
            members=members,
        )
        self._sync_from_response(response.data)
        return response

    def accept_feed_member_invite(
        self, user_id: Optional[str] = None, user: Optional[UserRequest] = None
    ) -> StreamResponse[AcceptFeedMemberInviteResponse]:
        response = self.client.accept_feed_member_invite(
            feed_group_id=self.feed_group, feed_id=self.id, user_id=user_id, user=user
        )
        self._sync_from_response(response.data)
        return response

    def query_feed_members(
        self,
        limit: Optional[int] = None,
        next: Optional[str] = None,
        prev: Optional[str] = None,
        sort: Optional[List[SortParamRequest]] = None,
        filter: Optional[Dict[str, object]] = None,
    ) -> StreamResponse[QueryFeedMembersResponse]:
        response = self.client.query_feed_members(
            feed_group_id=self.feed_group,
            feed_id=self.id,
            limit=limit,
            next=next,
            prev=prev,
            sort=sort,
            filter=filter,
        )
        self._sync_from_response(response.data)
        return response

    def reject_feed_member_invite(
        self, user_id: Optional[str] = None, user: Optional[UserRequest] = None
    ) -> StreamResponse[RejectFeedMemberInviteResponse]:
        response = self.client.reject_feed_member_invite(
            feed_group_id=self.feed_group, feed_id=self.id, user_id=user_id, user=user
        )
        self._sync_from_response(response.data)
        return response

    def query_pinned_activities(
        self,
        enrich_own_fields: Optional[bool] = None,
        limit: Optional[int] = None,
        next: Optional[str] = None,
        prev: Optional[str] = None,
        sort: Optional[List[SortParamRequest]] = None,
        filter: Optional[Dict[str, object]] = None,
    ) -> StreamResponse[QueryPinnedActivitiesResponse]:
        response = self.client.query_pinned_activities(
            feed_group_id=self.feed_group,
            feed_id=self.id,
            enrich_own_fields=enrich_own_fields,
            limit=limit,
            next=next,
            prev=prev,
            sort=sort,
            filter=filter,
        )
        self._sync_from_response(response.data)
        return response

    def get_feed_identifier(self):
        return self.feed_group + ":" + self.id

    create = get_or_create
