name: Python + uv setup
description: Checkout, set up uv/Python, and sync dev deps
inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.12"
  sync-flags:
    description: Extra flags for uv sync (e.g., --all-extras --dev)
    required: false
    default: "--all-extras --dev --frozen"
  working-directory:
    description: Directory to run in
    required: false
    default: "."
runs:
  using: composite
  steps:
    - name: Install the latest version of uv
      id: setup_uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}
        version: "latest"
        enable-cache: true
        prune-cache: false
        cache-suffix: ${{ inputs.python-version }}
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock

    - name: Log cache status
      shell: bash
      run: |
        echo "uv download cache hit: ${{ steps.setup_uv.outputs['cache-hit'] }}"
        echo ".venv cache hit: ${{ steps.cache_venv.outputs.cache-hit }}"

    - name: Install the project dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: uv sync ${{ inputs.sync-flags }}

