# Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

import hmac
import hashlib
import json
from typing import Union, Any, Dict
from .models import (
    CustomEvent,
    AppealAcceptedEvent,
    AppealCreatedEvent,
    AppealRejectedEvent,
    CallAcceptedEvent,
    BlockedUserEvent,
    ClosedCaptionEvent,
    CallClosedCaptionsFailedEvent,
    CallClosedCaptionsStartedEvent,
    CallClosedCaptionsStoppedEvent,
    CallCreatedEvent,
    CallDeletedEvent,
    CallDTMFEvent,
    CallEndedEvent,
    CallFrameRecordingFailedEvent,
    CallFrameRecordingFrameReadyEvent,
    CallFrameRecordingStartedEvent,
    CallFrameRecordingStoppedEvent,
    CallHLSBroadcastingFailedEvent,
    CallHLSBroadcastingStartedEvent,
    CallHLSBroadcastingStoppedEvent,
    KickedUserEvent,
    CallLiveStartedEvent,
    CallMemberAddedEvent,
    CallMemberRemovedEvent,
    CallMemberUpdatedEvent,
    CallMemberUpdatedPermissionEvent,
    CallMissedEvent,
    CallModerationBlurEvent,
    CallModerationWarningEvent,
    CallNotificationEvent,
    PermissionRequestEvent,
    UpdatedCallPermissionsEvent,
    CallReactionEvent,
    CallRecordingFailedEvent,
    CallRecordingReadyEvent,
    CallRecordingStartedEvent,
    CallRecordingStoppedEvent,
    CallRejectedEvent,
    CallRingEvent,
    CallRtmpBroadcastFailedEvent,
    CallRtmpBroadcastStartedEvent,
    CallRtmpBroadcastStoppedEvent,
    CallSessionEndedEvent,
    CallSessionParticipantCountsUpdatedEvent,
    CallSessionParticipantJoinedEvent,
    CallSessionParticipantLeftEvent,
    CallSessionStartedEvent,
    CallStatsReportReadyEvent,
    CallTranscriptionFailedEvent,
    CallTranscriptionReadyEvent,
    CallTranscriptionStartedEvent,
    CallTranscriptionStoppedEvent,
    UnblockedUserEvent,
    CallUpdatedEvent,
    CallUserFeedbackSubmittedEvent,
    CallUserMutedEvent,
    CampaignCompletedEvent,
    CampaignStartedEvent,
    ChannelCreatedEvent,
    ChannelDeletedEvent,
    ChannelFrozenEvent,
    ChannelHiddenEvent,
    MaxStreakChangedEvent,
    ChannelMutedEvent,
    ChannelTruncatedEvent,
    ChannelUnFrozenEvent,
    ChannelUnmutedEvent,
    ChannelUpdatedEvent,
    ChannelVisibleEvent,
    ChannelBatchCompletedEvent,
    ChannelBatchStartedEvent,
    CustomVideoEvent,
    AsyncBulkImageModerationEvent,
    AsyncExportChannelsEvent,
    AsyncExportModerationLogsEvent,
    AsyncExportErrorEvent,
    AsyncExportUsersEvent,
    ActivityAddedEvent,
    ActivityDeletedEvent,
    ActivityFeedbackEvent,
    ActivityMarkEvent,
    ActivityPinnedEvent,
    ActivityReactionAddedEvent,
    ActivityReactionDeletedEvent,
    ActivityReactionUpdatedEvent,
    ActivityRemovedFromFeedEvent,
    ActivityRestoredEvent,
    ActivityUnpinnedEvent,
    ActivityUpdatedEvent,
    BookmarkAddedEvent,
    BookmarkDeletedEvent,
    BookmarkUpdatedEvent,
    BookmarkFolderDeletedEvent,
    BookmarkFolderUpdatedEvent,
    CommentAddedEvent,
    CommentDeletedEvent,
    CommentReactionAddedEvent,
    CommentReactionDeletedEvent,
    CommentReactionUpdatedEvent,
    CommentUpdatedEvent,
    FeedCreatedEvent,
    FeedDeletedEvent,
    FeedUpdatedEvent,
    FeedGroupChangedEvent,
    FeedGroupDeletedEvent,
    FeedMemberAddedEvent,
    FeedMemberRemovedEvent,
    FeedMemberUpdatedEvent,
    FollowCreatedEvent,
    FollowDeletedEvent,
    FollowUpdatedEvent,
    NotificationFeedUpdatedEvent,
    StoriesFeedUpdatedEvent,
    FlagUpdatedEvent,
    IngressErrorEvent,
    IngressStartedEvent,
    IngressStoppedEvent,
    MemberAddedEvent,
    MemberRemovedEvent,
    MemberUpdatedEvent,
    MessageDeletedEvent,
    MessageFlaggedEvent,
    MessageNewEvent,
    PendingMessageEvent,
    MessageReadEvent,
    MessageUnblockedEvent,
    MessageUndeletedEvent,
    MessageUpdatedEvent,
    ModerationCustomActionEvent,
    ModerationFlaggedEvent,
    ModerationMarkReviewedEvent,
    ModerationCheckCompletedEvent,
    ModerationRulesTriggeredEvent,
    NotificationMarkUnreadEvent,
    ReminderNotificationEvent,
    NotificationThreadMessageNewEvent,
    ReactionDeletedEvent,
    ReactionNewEvent,
    ReactionUpdatedEvent,
    ReminderCreatedEvent,
    ReminderDeletedEvent,
    ReminderUpdatedEvent,
    ReviewQueueItemNewEvent,
    ReviewQueueItemUpdatedEvent,
    ThreadUpdatedEvent,
    UserBannedEvent,
    UserDeactivatedEvent,
    UserDeletedEvent,
    UserFlaggedEvent,
    UserMessagesDeletedEvent,
    UserMutedEvent,
    UserReactivatedEvent,
    UserUnbannedEvent,
    UserUnmutedEvent,
    UserUnreadReminderEvent,
    UserUpdatedEvent,
)


# Webhook event type constants
EVENT_TYPE_WILDCARD = "*"
EVENT_TYPE_APPEAL_ACCEPTED = "appeal.accepted"
EVENT_TYPE_APPEAL_CREATED = "appeal.created"
EVENT_TYPE_APPEAL_REJECTED = "appeal.rejected"
EVENT_TYPE_CALL_ACCEPTED = "call.accepted"
EVENT_TYPE_CALL_BLOCKED_USER = "call.blocked_user"
EVENT_TYPE_CALL_CLOSED_CAPTION = "call.closed_caption"
EVENT_TYPE_CALL_CLOSED_CAPTIONS_FAILED = "call.closed_captions_failed"
EVENT_TYPE_CALL_CLOSED_CAPTIONS_STARTED = "call.closed_captions_started"
EVENT_TYPE_CALL_CLOSED_CAPTIONS_STOPPED = "call.closed_captions_stopped"
EVENT_TYPE_CALL_CREATED = "call.created"
EVENT_TYPE_CALL_DELETED = "call.deleted"
EVENT_TYPE_CALL_DTMF = "call.dtmf"
EVENT_TYPE_CALL_ENDED = "call.ended"
EVENT_TYPE_CALL_FRAME_RECORDING_FAILED = "call.frame_recording_failed"
EVENT_TYPE_CALL_FRAME_RECORDING_READY = "call.frame_recording_ready"
EVENT_TYPE_CALL_FRAME_RECORDING_STARTED = "call.frame_recording_started"
EVENT_TYPE_CALL_FRAME_RECORDING_STOPPED = "call.frame_recording_stopped"
EVENT_TYPE_CALL_HLS_BROADCASTING_FAILED = "call.hls_broadcasting_failed"
EVENT_TYPE_CALL_HLS_BROADCASTING_STARTED = "call.hls_broadcasting_started"
EVENT_TYPE_CALL_HLS_BROADCASTING_STOPPED = "call.hls_broadcasting_stopped"
EVENT_TYPE_CALL_KICKED_USER = "call.kicked_user"
EVENT_TYPE_CALL_LIVE_STARTED = "call.live_started"
EVENT_TYPE_CALL_MEMBER_ADDED = "call.member_added"
EVENT_TYPE_CALL_MEMBER_REMOVED = "call.member_removed"
EVENT_TYPE_CALL_MEMBER_UPDATED = "call.member_updated"
EVENT_TYPE_CALL_MEMBER_UPDATED_PERMISSION = "call.member_updated_permission"
EVENT_TYPE_CALL_MISSED = "call.missed"
EVENT_TYPE_CALL_MODERATION_BLUR = "call.moderation_blur"
EVENT_TYPE_CALL_MODERATION_WARNING = "call.moderation_warning"
EVENT_TYPE_CALL_NOTIFICATION = "call.notification"
EVENT_TYPE_CALL_PERMISSION_REQUEST = "call.permission_request"
EVENT_TYPE_CALL_PERMISSIONS_UPDATED = "call.permissions_updated"
EVENT_TYPE_CALL_REACTION_NEW = "call.reaction_new"
EVENT_TYPE_CALL_RECORDING_FAILED = "call.recording_failed"
EVENT_TYPE_CALL_RECORDING_READY = "call.recording_ready"
EVENT_TYPE_CALL_RECORDING_STARTED = "call.recording_started"
EVENT_TYPE_CALL_RECORDING_STOPPED = "call.recording_stopped"
EVENT_TYPE_CALL_REJECTED = "call.rejected"
EVENT_TYPE_CALL_RING = "call.ring"
EVENT_TYPE_CALL_RTMP_BROADCAST_FAILED = "call.rtmp_broadcast_failed"
EVENT_TYPE_CALL_RTMP_BROADCAST_STARTED = "call.rtmp_broadcast_started"
EVENT_TYPE_CALL_RTMP_BROADCAST_STOPPED = "call.rtmp_broadcast_stopped"
EVENT_TYPE_CALL_SESSION_ENDED = "call.session_ended"
EVENT_TYPE_CALL_SESSION_PARTICIPANT_COUNT_UPDATED = (
    "call.session_participant_count_updated"
)
EVENT_TYPE_CALL_SESSION_PARTICIPANT_JOINED = "call.session_participant_joined"
EVENT_TYPE_CALL_SESSION_PARTICIPANT_LEFT = "call.session_participant_left"
EVENT_TYPE_CALL_SESSION_STARTED = "call.session_started"
EVENT_TYPE_CALL_STATS_REPORT_READY = "call.stats_report_ready"
EVENT_TYPE_CALL_TRANSCRIPTION_FAILED = "call.transcription_failed"
EVENT_TYPE_CALL_TRANSCRIPTION_READY = "call.transcription_ready"
EVENT_TYPE_CALL_TRANSCRIPTION_STARTED = "call.transcription_started"
EVENT_TYPE_CALL_TRANSCRIPTION_STOPPED = "call.transcription_stopped"
EVENT_TYPE_CALL_UNBLOCKED_USER = "call.unblocked_user"
EVENT_TYPE_CALL_UPDATED = "call.updated"
EVENT_TYPE_CALL_USER_FEEDBACK_SUBMITTED = "call.user_feedback_submitted"
EVENT_TYPE_CALL_USER_MUTED = "call.user_muted"
EVENT_TYPE_CAMPAIGN_COMPLETED = "campaign.completed"
EVENT_TYPE_CAMPAIGN_STARTED = "campaign.started"
EVENT_TYPE_CHANNEL_CREATED = "channel.created"
EVENT_TYPE_CHANNEL_DELETED = "channel.deleted"
EVENT_TYPE_CHANNEL_FROZEN = "channel.frozen"
EVENT_TYPE_CHANNEL_HIDDEN = "channel.hidden"
EVENT_TYPE_CHANNEL_MAX_STREAK_CHANGED = "channel.max_streak_changed"
EVENT_TYPE_CHANNEL_MUTED = "channel.muted"
EVENT_TYPE_CHANNEL_TRUNCATED = "channel.truncated"
EVENT_TYPE_CHANNEL_UNFROZEN = "channel.unfrozen"
EVENT_TYPE_CHANNEL_UNMUTED = "channel.unmuted"
EVENT_TYPE_CHANNEL_UPDATED = "channel.updated"
EVENT_TYPE_CHANNEL_VISIBLE = "channel.visible"
EVENT_TYPE_CHANNEL_BATCH_UPDATE_COMPLETED = "channel_batch_update.completed"
EVENT_TYPE_CHANNEL_BATCH_UPDATE_STARTED = "channel_batch_update.started"
EVENT_TYPE_CUSTOM = "custom"
EVENT_TYPE_EXPORT_BULK_IMAGE_MODERATION_ERROR = "export.bulk_image_moderation.error"
EVENT_TYPE_EXPORT_BULK_IMAGE_MODERATION_SUCCESS = "export.bulk_image_moderation.success"
EVENT_TYPE_EXPORT_CHANNELS_ERROR = "export.channels.error"
EVENT_TYPE_EXPORT_CHANNELS_SUCCESS = "export.channels.success"
EVENT_TYPE_EXPORT_MODERATION_LOGS_ERROR = "export.moderation_logs.error"
EVENT_TYPE_EXPORT_MODERATION_LOGS_SUCCESS = "export.moderation_logs.success"
EVENT_TYPE_EXPORT_USERS_ERROR = "export.users.error"
EVENT_TYPE_EXPORT_USERS_SUCCESS = "export.users.success"
EVENT_TYPE_FEEDS_ACTIVITY_ADDED = "feeds.activity.added"
EVENT_TYPE_FEEDS_ACTIVITY_DELETED = "feeds.activity.deleted"
EVENT_TYPE_FEEDS_ACTIVITY_FEEDBACK = "feeds.activity.feedback"
EVENT_TYPE_FEEDS_ACTIVITY_MARKED = "feeds.activity.marked"
EVENT_TYPE_FEEDS_ACTIVITY_PINNED = "feeds.activity.pinned"
EVENT_TYPE_FEEDS_ACTIVITY_REACTION_ADDED = "feeds.activity.reaction.added"
EVENT_TYPE_FEEDS_ACTIVITY_REACTION_DELETED = "feeds.activity.reaction.deleted"
EVENT_TYPE_FEEDS_ACTIVITY_REACTION_UPDATED = "feeds.activity.reaction.updated"
EVENT_TYPE_FEEDS_ACTIVITY_REMOVED_FROM_FEED = "feeds.activity.removed_from_feed"
EVENT_TYPE_FEEDS_ACTIVITY_RESTORED = "feeds.activity.restored"
EVENT_TYPE_FEEDS_ACTIVITY_UNPINNED = "feeds.activity.unpinned"
EVENT_TYPE_FEEDS_ACTIVITY_UPDATED = "feeds.activity.updated"
EVENT_TYPE_FEEDS_BOOKMARK_ADDED = "feeds.bookmark.added"
EVENT_TYPE_FEEDS_BOOKMARK_DELETED = "feeds.bookmark.deleted"
EVENT_TYPE_FEEDS_BOOKMARK_UPDATED = "feeds.bookmark.updated"
EVENT_TYPE_FEEDS_BOOKMARK_FOLDER_DELETED = "feeds.bookmark_folder.deleted"
EVENT_TYPE_FEEDS_BOOKMARK_FOLDER_UPDATED = "feeds.bookmark_folder.updated"
EVENT_TYPE_FEEDS_COMMENT_ADDED = "feeds.comment.added"
EVENT_TYPE_FEEDS_COMMENT_DELETED = "feeds.comment.deleted"
EVENT_TYPE_FEEDS_COMMENT_REACTION_ADDED = "feeds.comment.reaction.added"
EVENT_TYPE_FEEDS_COMMENT_REACTION_DELETED = "feeds.comment.reaction.deleted"
EVENT_TYPE_FEEDS_COMMENT_REACTION_UPDATED = "feeds.comment.reaction.updated"
EVENT_TYPE_FEEDS_COMMENT_UPDATED = "feeds.comment.updated"
EVENT_TYPE_FEEDS_FEED_CREATED = "feeds.feed.created"
EVENT_TYPE_FEEDS_FEED_DELETED = "feeds.feed.deleted"
EVENT_TYPE_FEEDS_FEED_UPDATED = "feeds.feed.updated"
EVENT_TYPE_FEEDS_FEED_GROUP_CHANGED = "feeds.feed_group.changed"
EVENT_TYPE_FEEDS_FEED_GROUP_DELETED = "feeds.feed_group.deleted"
EVENT_TYPE_FEEDS_FEED_MEMBER_ADDED = "feeds.feed_member.added"
EVENT_TYPE_FEEDS_FEED_MEMBER_REMOVED = "feeds.feed_member.removed"
EVENT_TYPE_FEEDS_FEED_MEMBER_UPDATED = "feeds.feed_member.updated"
EVENT_TYPE_FEEDS_FOLLOW_CREATED = "feeds.follow.created"
EVENT_TYPE_FEEDS_FOLLOW_DELETED = "feeds.follow.deleted"
EVENT_TYPE_FEEDS_FOLLOW_UPDATED = "feeds.follow.updated"
EVENT_TYPE_FEEDS_NOTIFICATION_FEED_UPDATED = "feeds.notification_feed.updated"
EVENT_TYPE_FEEDS_STORIES_FEED_UPDATED = "feeds.stories_feed.updated"
EVENT_TYPE_FLAG_UPDATED = "flag.updated"
EVENT_TYPE_INGRESS_ERROR = "ingress.error"
EVENT_TYPE_INGRESS_STARTED = "ingress.started"
EVENT_TYPE_INGRESS_STOPPED = "ingress.stopped"
EVENT_TYPE_MEMBER_ADDED = "member.added"
EVENT_TYPE_MEMBER_REMOVED = "member.removed"
EVENT_TYPE_MEMBER_UPDATED = "member.updated"
EVENT_TYPE_MESSAGE_DELETED = "message.deleted"
EVENT_TYPE_MESSAGE_FLAGGED = "message.flagged"
EVENT_TYPE_MESSAGE_NEW = "message.new"
EVENT_TYPE_MESSAGE_PENDING = "message.pending"
EVENT_TYPE_MESSAGE_READ = "message.read"
EVENT_TYPE_MESSAGE_UNBLOCKED = "message.unblocked"
EVENT_TYPE_MESSAGE_UNDELETED = "message.undeleted"
EVENT_TYPE_MESSAGE_UPDATED = "message.updated"
EVENT_TYPE_MODERATION_CUSTOM_ACTION = "moderation.custom_action"
EVENT_TYPE_MODERATION_FLAGGED = "moderation.flagged"
EVENT_TYPE_MODERATION_MARK_REVIEWED = "moderation.mark_reviewed"
EVENT_TYPE_MODERATION_CHECK_COMPLETED = "moderation_check.completed"
EVENT_TYPE_MODERATION_RULE_TRIGGERED = "moderation_rule.triggered"
EVENT_TYPE_NOTIFICATION_MARK_UNREAD = "notification.mark_unread"
EVENT_TYPE_NOTIFICATION_REMINDER_DUE = "notification.reminder_due"
EVENT_TYPE_NOTIFICATION_THREAD_MESSAGE_NEW = "notification.thread_message_new"
EVENT_TYPE_REACTION_DELETED = "reaction.deleted"
EVENT_TYPE_REACTION_NEW = "reaction.new"
EVENT_TYPE_REACTION_UPDATED = "reaction.updated"
EVENT_TYPE_REMINDER_CREATED = "reminder.created"
EVENT_TYPE_REMINDER_DELETED = "reminder.deleted"
EVENT_TYPE_REMINDER_UPDATED = "reminder.updated"
EVENT_TYPE_REVIEW_QUEUE_ITEM_NEW = "review_queue_item.new"
EVENT_TYPE_REVIEW_QUEUE_ITEM_UPDATED = "review_queue_item.updated"
EVENT_TYPE_THREAD_UPDATED = "thread.updated"
EVENT_TYPE_USER_BANNED = "user.banned"
EVENT_TYPE_USER_DEACTIVATED = "user.deactivated"
EVENT_TYPE_USER_DELETED = "user.deleted"
EVENT_TYPE_USER_FLAGGED = "user.flagged"
EVENT_TYPE_USER_MESSAGES_DELETED = "user.messages.deleted"
EVENT_TYPE_USER_MUTED = "user.muted"
EVENT_TYPE_USER_REACTIVATED = "user.reactivated"
EVENT_TYPE_USER_UNBANNED = "user.unbanned"
EVENT_TYPE_USER_UNMUTED = "user.unmuted"
EVENT_TYPE_USER_UNREAD_MESSAGE_REMINDER = "user.unread_message_reminder"
EVENT_TYPE_USER_UPDATED = "user.updated"


def get_event_type(raw_event: Union[bytes, str, Dict[str, Any]]) -> str:
    """
    Extract the event type from a raw webhook payload.

    Args:
        raw_event: The raw webhook payload

    Returns:
        The event type string (e.g., "message.new"), or empty string if parsing fails
    """
    if isinstance(raw_event, dict):
        return raw_event.get("type", "")

    try:
        if isinstance(raw_event, bytes):
            raw_event = raw_event.decode("utf-8")
        data = json.loads(raw_event)
        return data.get("type", "")
    except (json.JSONDecodeError, UnicodeDecodeError, AttributeError):
        return ""


def parse_webhook_event(raw_event: Union[bytes, str, Dict[str, Any]]) -> Any:
    """
    Deserialize a raw webhook payload into a typed event object.

    Args:
        raw_event: The raw webhook payload

    Returns:
        A typed event object corresponding to the event type

    Raises:
        ValueError: If the event type is unknown or deserialization fails
    """
    try:
        if isinstance(raw_event, dict):
            data = raw_event
        elif isinstance(raw_event, bytes):
            data = json.loads(raw_event.decode("utf-8"))
        else:
            data = json.loads(raw_event)
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        raise ValueError(f"Failed to parse webhook payload: {e}")

    event_type = data.get("type")
    if not event_type:
        raise ValueError("Webhook payload missing 'type' field")

    event_class = _get_event_class(event_type)
    if event_class is None:
        raise ValueError(f"Unknown webhook event type: {event_type}")

    try:
        return event_class.from_dict(data, infer_missing=True)
    except Exception as e:
        raise ValueError(f"Failed to deserialize webhook event: {e}")


def _get_event_class(event_type: str):
    """Map event type to event class."""
    event_map = {
        "*": CustomEvent,
        "appeal.accepted": AppealAcceptedEvent,
        "appeal.created": AppealCreatedEvent,
        "appeal.rejected": AppealRejectedEvent,
        "call.accepted": CallAcceptedEvent,
        "call.blocked_user": BlockedUserEvent,
        "call.closed_caption": ClosedCaptionEvent,
        "call.closed_captions_failed": CallClosedCaptionsFailedEvent,
        "call.closed_captions_started": CallClosedCaptionsStartedEvent,
        "call.closed_captions_stopped": CallClosedCaptionsStoppedEvent,
        "call.created": CallCreatedEvent,
        "call.deleted": CallDeletedEvent,
        "call.dtmf": CallDTMFEvent,
        "call.ended": CallEndedEvent,
        "call.frame_recording_failed": CallFrameRecordingFailedEvent,
        "call.frame_recording_ready": CallFrameRecordingFrameReadyEvent,
        "call.frame_recording_started": CallFrameRecordingStartedEvent,
        "call.frame_recording_stopped": CallFrameRecordingStoppedEvent,
        "call.hls_broadcasting_failed": CallHLSBroadcastingFailedEvent,
        "call.hls_broadcasting_started": CallHLSBroadcastingStartedEvent,
        "call.hls_broadcasting_stopped": CallHLSBroadcastingStoppedEvent,
        "call.kicked_user": KickedUserEvent,
        "call.live_started": CallLiveStartedEvent,
        "call.member_added": CallMemberAddedEvent,
        "call.member_removed": CallMemberRemovedEvent,
        "call.member_updated": CallMemberUpdatedEvent,
        "call.member_updated_permission": CallMemberUpdatedPermissionEvent,
        "call.missed": CallMissedEvent,
        "call.moderation_blur": CallModerationBlurEvent,
        "call.moderation_warning": CallModerationWarningEvent,
        "call.notification": CallNotificationEvent,
        "call.permission_request": PermissionRequestEvent,
        "call.permissions_updated": UpdatedCallPermissionsEvent,
        "call.reaction_new": CallReactionEvent,
        "call.recording_failed": CallRecordingFailedEvent,
        "call.recording_ready": CallRecordingReadyEvent,
        "call.recording_started": CallRecordingStartedEvent,
        "call.recording_stopped": CallRecordingStoppedEvent,
        "call.rejected": CallRejectedEvent,
        "call.ring": CallRingEvent,
        "call.rtmp_broadcast_failed": CallRtmpBroadcastFailedEvent,
        "call.rtmp_broadcast_started": CallRtmpBroadcastStartedEvent,
        "call.rtmp_broadcast_stopped": CallRtmpBroadcastStoppedEvent,
        "call.session_ended": CallSessionEndedEvent,
        "call.session_participant_count_updated": CallSessionParticipantCountsUpdatedEvent,
        "call.session_participant_joined": CallSessionParticipantJoinedEvent,
        "call.session_participant_left": CallSessionParticipantLeftEvent,
        "call.session_started": CallSessionStartedEvent,
        "call.stats_report_ready": CallStatsReportReadyEvent,
        "call.transcription_failed": CallTranscriptionFailedEvent,
        "call.transcription_ready": CallTranscriptionReadyEvent,
        "call.transcription_started": CallTranscriptionStartedEvent,
        "call.transcription_stopped": CallTranscriptionStoppedEvent,
        "call.unblocked_user": UnblockedUserEvent,
        "call.updated": CallUpdatedEvent,
        "call.user_feedback_submitted": CallUserFeedbackSubmittedEvent,
        "call.user_muted": CallUserMutedEvent,
        "campaign.completed": CampaignCompletedEvent,
        "campaign.started": CampaignStartedEvent,
        "channel.created": ChannelCreatedEvent,
        "channel.deleted": ChannelDeletedEvent,
        "channel.frozen": ChannelFrozenEvent,
        "channel.hidden": ChannelHiddenEvent,
        "channel.max_streak_changed": MaxStreakChangedEvent,
        "channel.muted": ChannelMutedEvent,
        "channel.truncated": ChannelTruncatedEvent,
        "channel.unfrozen": ChannelUnFrozenEvent,
        "channel.unmuted": ChannelUnmutedEvent,
        "channel.updated": ChannelUpdatedEvent,
        "channel.visible": ChannelVisibleEvent,
        "channel_batch_update.completed": ChannelBatchCompletedEvent,
        "channel_batch_update.started": ChannelBatchStartedEvent,
        "custom": CustomVideoEvent,
        "export.bulk_image_moderation.error": AsyncExportErrorEvent,
        "export.bulk_image_moderation.success": AsyncBulkImageModerationEvent,
        "export.channels.error": AsyncExportErrorEvent,
        "export.channels.success": AsyncExportChannelsEvent,
        "export.moderation_logs.error": AsyncExportErrorEvent,
        "export.moderation_logs.success": AsyncExportModerationLogsEvent,
        "export.users.error": AsyncExportErrorEvent,
        "export.users.success": AsyncExportUsersEvent,
        "feeds.activity.added": ActivityAddedEvent,
        "feeds.activity.deleted": ActivityDeletedEvent,
        "feeds.activity.feedback": ActivityFeedbackEvent,
        "feeds.activity.marked": ActivityMarkEvent,
        "feeds.activity.pinned": ActivityPinnedEvent,
        "feeds.activity.reaction.added": ActivityReactionAddedEvent,
        "feeds.activity.reaction.deleted": ActivityReactionDeletedEvent,
        "feeds.activity.reaction.updated": ActivityReactionUpdatedEvent,
        "feeds.activity.removed_from_feed": ActivityRemovedFromFeedEvent,
        "feeds.activity.restored": ActivityRestoredEvent,
        "feeds.activity.unpinned": ActivityUnpinnedEvent,
        "feeds.activity.updated": ActivityUpdatedEvent,
        "feeds.bookmark.added": BookmarkAddedEvent,
        "feeds.bookmark.deleted": BookmarkDeletedEvent,
        "feeds.bookmark.updated": BookmarkUpdatedEvent,
        "feeds.bookmark_folder.deleted": BookmarkFolderDeletedEvent,
        "feeds.bookmark_folder.updated": BookmarkFolderUpdatedEvent,
        "feeds.comment.added": CommentAddedEvent,
        "feeds.comment.deleted": CommentDeletedEvent,
        "feeds.comment.reaction.added": CommentReactionAddedEvent,
        "feeds.comment.reaction.deleted": CommentReactionDeletedEvent,
        "feeds.comment.reaction.updated": CommentReactionUpdatedEvent,
        "feeds.comment.updated": CommentUpdatedEvent,
        "feeds.feed.created": FeedCreatedEvent,
        "feeds.feed.deleted": FeedDeletedEvent,
        "feeds.feed.updated": FeedUpdatedEvent,
        "feeds.feed_group.changed": FeedGroupChangedEvent,
        "feeds.feed_group.deleted": FeedGroupDeletedEvent,
        "feeds.feed_member.added": FeedMemberAddedEvent,
        "feeds.feed_member.removed": FeedMemberRemovedEvent,
        "feeds.feed_member.updated": FeedMemberUpdatedEvent,
        "feeds.follow.created": FollowCreatedEvent,
        "feeds.follow.deleted": FollowDeletedEvent,
        "feeds.follow.updated": FollowUpdatedEvent,
        "feeds.notification_feed.updated": NotificationFeedUpdatedEvent,
        "feeds.stories_feed.updated": StoriesFeedUpdatedEvent,
        "flag.updated": FlagUpdatedEvent,
        "ingress.error": IngressErrorEvent,
        "ingress.started": IngressStartedEvent,
        "ingress.stopped": IngressStoppedEvent,
        "member.added": MemberAddedEvent,
        "member.removed": MemberRemovedEvent,
        "member.updated": MemberUpdatedEvent,
        "message.deleted": MessageDeletedEvent,
        "message.flagged": MessageFlaggedEvent,
        "message.new": MessageNewEvent,
        "message.pending": PendingMessageEvent,
        "message.read": MessageReadEvent,
        "message.unblocked": MessageUnblockedEvent,
        "message.undeleted": MessageUndeletedEvent,
        "message.updated": MessageUpdatedEvent,
        "moderation.custom_action": ModerationCustomActionEvent,
        "moderation.flagged": ModerationFlaggedEvent,
        "moderation.mark_reviewed": ModerationMarkReviewedEvent,
        "moderation_check.completed": ModerationCheckCompletedEvent,
        "moderation_rule.triggered": ModerationRulesTriggeredEvent,
        "notification.mark_unread": NotificationMarkUnreadEvent,
        "notification.reminder_due": ReminderNotificationEvent,
        "notification.thread_message_new": NotificationThreadMessageNewEvent,
        "reaction.deleted": ReactionDeletedEvent,
        "reaction.new": ReactionNewEvent,
        "reaction.updated": ReactionUpdatedEvent,
        "reminder.created": ReminderCreatedEvent,
        "reminder.deleted": ReminderDeletedEvent,
        "reminder.updated": ReminderUpdatedEvent,
        "review_queue_item.new": ReviewQueueItemNewEvent,
        "review_queue_item.updated": ReviewQueueItemUpdatedEvent,
        "thread.updated": ThreadUpdatedEvent,
        "user.banned": UserBannedEvent,
        "user.deactivated": UserDeactivatedEvent,
        "user.deleted": UserDeletedEvent,
        "user.flagged": UserFlaggedEvent,
        "user.messages.deleted": UserMessagesDeletedEvent,
        "user.muted": UserMutedEvent,
        "user.reactivated": UserReactivatedEvent,
        "user.unbanned": UserUnbannedEvent,
        "user.unmuted": UserUnmutedEvent,
        "user.unread_message_reminder": UserUnreadReminderEvent,
        "user.updated": UserUpdatedEvent,
    }
    return event_map.get(event_type)


def verify_webhook_signature(
    body: Union[bytes, str], signature: str, secret: str
) -> bool:
    """
    Verify the HMAC-SHA256 signature of a webhook payload.

    Args:
        body: The raw request body (bytes or UTF-8 string)
        signature: The signature from the X-Signature header
        secret: Your webhook secret (found in the Stream Dashboard)

    Returns:
        True if the signature is valid, False otherwise
    """
    if isinstance(body, str):
        body = body.encode("utf-8")

    h = hmac.new(secret.encode("utf-8"), body, hashlib.sha256)
    expected = h.hexdigest()
    return hmac.compare_digest(signature, expected)
