# Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

import hmac
import hashlib
import json
from typing import Union, Any, Dict
from .models.custom_event import CustomEvent
from .models.appeal_accepted_event import AppealAcceptedEvent
from .models.appeal_created_event import AppealCreatedEvent
from .models.appeal_rejected_event import AppealRejectedEvent
from .models.call_accepted_event import CallAcceptedEvent
from .models.blocked_user_event import BlockedUserEvent
from .models.closed_caption_event import ClosedCaptionEvent
from .models.call_closed_captions_failed_event import CallClosedCaptionsFailedEvent
from .models.call_closed_captions_started_event import CallClosedCaptionsStartedEvent
from .models.call_closed_captions_stopped_event import CallClosedCaptionsStoppedEvent
from .models.call_created_event import CallCreatedEvent
from .models.call_deleted_event import CallDeletedEvent
from .models.call_ended_event import CallEndedEvent
from .models.call_frame_recording_failed_event import CallFrameRecordingFailedEvent
from .models.call_frame_recording_frame_ready_event import (
    CallFrameRecordingFrameReadyEvent,
)
from .models.call_frame_recording_started_event import CallFrameRecordingStartedEvent
from .models.call_frame_recording_stopped_event import CallFrameRecordingStoppedEvent
from .models.call_hls_broadcasting_failed_event import CallHLSBroadcastingFailedEvent
from .models.call_hls_broadcasting_started_event import CallHLSBroadcastingStartedEvent
from .models.call_hls_broadcasting_stopped_event import CallHLSBroadcastingStoppedEvent
from .models.kicked_user_event import KickedUserEvent
from .models.call_live_started_event import CallLiveStartedEvent
from .models.call_member_added_event import CallMemberAddedEvent
from .models.call_member_removed_event import CallMemberRemovedEvent
from .models.call_member_updated_event import CallMemberUpdatedEvent
from .models.call_member_updated_permission_event import (
    CallMemberUpdatedPermissionEvent,
)
from .models.call_missed_event import CallMissedEvent
from .models.call_moderation_blur_event import CallModerationBlurEvent
from .models.call_moderation_warning_event import CallModerationWarningEvent
from .models.call_notification_event import CallNotificationEvent
from .models.permission_request_event import PermissionRequestEvent
from .models.updated_call_permissions_event import UpdatedCallPermissionsEvent
from .models.call_reaction_event import CallReactionEvent
from .models.call_recording_failed_event import CallRecordingFailedEvent
from .models.call_recording_ready_event import CallRecordingReadyEvent
from .models.call_recording_started_event import CallRecordingStartedEvent
from .models.call_recording_stopped_event import CallRecordingStoppedEvent
from .models.call_rejected_event import CallRejectedEvent
from .models.call_ring_event import CallRingEvent
from .models.call_rtmp_broadcast_failed_event import CallRtmpBroadcastFailedEvent
from .models.call_rtmp_broadcast_started_event import CallRtmpBroadcastStartedEvent
from .models.call_rtmp_broadcast_stopped_event import CallRtmpBroadcastStoppedEvent
from .models.call_session_ended_event import CallSessionEndedEvent
from .models.call_session_participant_counts_updated_event import (
    CallSessionParticipantCountsUpdatedEvent,
)
from .models.call_session_participant_joined_event import (
    CallSessionParticipantJoinedEvent,
)
from .models.call_session_participant_left_event import CallSessionParticipantLeftEvent
from .models.call_session_started_event import CallSessionStartedEvent
from .models.call_stats_report_ready_event import CallStatsReportReadyEvent
from .models.call_transcription_failed_event import CallTranscriptionFailedEvent
from .models.call_transcription_ready_event import CallTranscriptionReadyEvent
from .models.call_transcription_started_event import CallTranscriptionStartedEvent
from .models.call_transcription_stopped_event import CallTranscriptionStoppedEvent
from .models.unblocked_user_event import UnblockedUserEvent
from .models.call_updated_event import CallUpdatedEvent
from .models.call_user_feedback_submitted_event import CallUserFeedbackSubmittedEvent
from .models.call_user_muted_event import CallUserMutedEvent
from .models.campaign_completed_event import CampaignCompletedEvent
from .models.campaign_started_event import CampaignStartedEvent
from .models.channel_created_event import ChannelCreatedEvent
from .models.channel_deleted_event import ChannelDeletedEvent
from .models.channel_frozen_event import ChannelFrozenEvent
from .models.channel_hidden_event import ChannelHiddenEvent
from .models.max_streak_changed_event import MaxStreakChangedEvent
from .models.channel_muted_event import ChannelMutedEvent
from .models.channel_truncated_event import ChannelTruncatedEvent
from .models.channel_un_frozen_event import ChannelUnFrozenEvent
from .models.channel_unmuted_event import ChannelUnmutedEvent
from .models.channel_updated_event import ChannelUpdatedEvent
from .models.channel_visible_event import ChannelVisibleEvent
from .models.channel_batch_completed_event import ChannelBatchCompletedEvent
from .models.channel_batch_started_event import ChannelBatchStartedEvent
from .models.custom_video_event import CustomVideoEvent
from .models.async_export_error_event import AsyncExportErrorEvent
from .models.async_bulk_image_moderation_event import AsyncBulkImageModerationEvent
from .models.async_export_channels_event import AsyncExportChannelsEvent
from .models.async_export_moderation_logs_event import AsyncExportModerationLogsEvent
from .models.async_export_users_event import AsyncExportUsersEvent
from .models.activity_added_event import ActivityAddedEvent
from .models.activity_deleted_event import ActivityDeletedEvent
from .models.activity_feedback_event import ActivityFeedbackEvent
from .models.activity_mark_event import ActivityMarkEvent
from .models.activity_pinned_event import ActivityPinnedEvent
from .models.activity_reaction_added_event import ActivityReactionAddedEvent
from .models.activity_reaction_deleted_event import ActivityReactionDeletedEvent
from .models.activity_reaction_updated_event import ActivityReactionUpdatedEvent
from .models.activity_removed_from_feed_event import ActivityRemovedFromFeedEvent
from .models.activity_unpinned_event import ActivityUnpinnedEvent
from .models.activity_updated_event import ActivityUpdatedEvent
from .models.bookmark_added_event import BookmarkAddedEvent
from .models.bookmark_deleted_event import BookmarkDeletedEvent
from .models.bookmark_updated_event import BookmarkUpdatedEvent
from .models.bookmark_folder_deleted_event import BookmarkFolderDeletedEvent
from .models.bookmark_folder_updated_event import BookmarkFolderUpdatedEvent
from .models.comment_added_event import CommentAddedEvent
from .models.comment_deleted_event import CommentDeletedEvent
from .models.comment_reaction_added_event import CommentReactionAddedEvent
from .models.comment_reaction_deleted_event import CommentReactionDeletedEvent
from .models.comment_reaction_updated_event import CommentReactionUpdatedEvent
from .models.comment_updated_event import CommentUpdatedEvent
from .models.feed_created_event import FeedCreatedEvent
from .models.feed_deleted_event import FeedDeletedEvent
from .models.feed_updated_event import FeedUpdatedEvent
from .models.feed_group_changed_event import FeedGroupChangedEvent
from .models.feed_group_deleted_event import FeedGroupDeletedEvent
from .models.feed_member_added_event import FeedMemberAddedEvent
from .models.feed_member_removed_event import FeedMemberRemovedEvent
from .models.feed_member_updated_event import FeedMemberUpdatedEvent
from .models.follow_created_event import FollowCreatedEvent
from .models.follow_deleted_event import FollowDeletedEvent
from .models.follow_updated_event import FollowUpdatedEvent
from .models.notification_feed_updated_event import NotificationFeedUpdatedEvent
from .models.stories_feed_updated_event import StoriesFeedUpdatedEvent
from .models.flag_updated_event import FlagUpdatedEvent
from .models.member_added_event import MemberAddedEvent
from .models.member_removed_event import MemberRemovedEvent
from .models.member_updated_event import MemberUpdatedEvent
from .models.message_deleted_event import MessageDeletedEvent
from .models.message_flagged_event import MessageFlaggedEvent
from .models.message_new_event import MessageNewEvent
from .models.pending_message_event import PendingMessageEvent
from .models.message_read_event import MessageReadEvent
from .models.message_unblocked_event import MessageUnblockedEvent
from .models.message_undeleted_event import MessageUndeletedEvent
from .models.message_updated_event import MessageUpdatedEvent
from .models.moderation_custom_action_event import ModerationCustomActionEvent
from .models.moderation_flagged_event import ModerationFlaggedEvent
from .models.moderation_mark_reviewed_event import ModerationMarkReviewedEvent
from .models.moderation_check_completed_event import ModerationCheckCompletedEvent
from .models.notification_mark_unread_event import NotificationMarkUnreadEvent
from .models.reminder_notification_event import ReminderNotificationEvent
from .models.notification_thread_message_new_event import (
    NotificationThreadMessageNewEvent,
)
from .models.reaction_deleted_event import ReactionDeletedEvent
from .models.reaction_new_event import ReactionNewEvent
from .models.reaction_updated_event import ReactionUpdatedEvent
from .models.reminder_created_event import ReminderCreatedEvent
from .models.reminder_deleted_event import ReminderDeletedEvent
from .models.reminder_updated_event import ReminderUpdatedEvent
from .models.review_queue_item_new_event import ReviewQueueItemNewEvent
from .models.review_queue_item_updated_event import ReviewQueueItemUpdatedEvent
from .models.thread_updated_event import ThreadUpdatedEvent
from .models.user_banned_event import UserBannedEvent
from .models.user_deactivated_event import UserDeactivatedEvent
from .models.user_deleted_event import UserDeletedEvent
from .models.user_flagged_event import UserFlaggedEvent
from .models.user_messages_deleted_event import UserMessagesDeletedEvent
from .models.user_muted_event import UserMutedEvent
from .models.user_reactivated_event import UserReactivatedEvent
from .models.user_unbanned_event import UserUnbannedEvent
from .models.user_unmuted_event import UserUnmutedEvent
from .models.user_unread_reminder_event import UserUnreadReminderEvent
from .models.user_updated_event import UserUpdatedEvent


# Webhook event type constants
EVENT_TYPE_WILDCARD = "*"
EVENT_TYPE_APPEAL_ACCEPTED = "appeal.accepted"
EVENT_TYPE_APPEAL_CREATED = "appeal.created"
EVENT_TYPE_APPEAL_REJECTED = "appeal.rejected"
EVENT_TYPE_CALL_ACCEPTED = "call.accepted"
EVENT_TYPE_CALL_BLOCKED_USER = "call.blocked_user"
EVENT_TYPE_CALL_CLOSED_CAPTION = "call.closed_caption"
EVENT_TYPE_CALL_CLOSED_CAPTIONS_FAILED = "call.closed_captions_failed"
EVENT_TYPE_CALL_CLOSED_CAPTIONS_STARTED = "call.closed_captions_started"
EVENT_TYPE_CALL_CLOSED_CAPTIONS_STOPPED = "call.closed_captions_stopped"
EVENT_TYPE_CALL_CREATED = "call.created"
EVENT_TYPE_CALL_DELETED = "call.deleted"
EVENT_TYPE_CALL_ENDED = "call.ended"
EVENT_TYPE_CALL_FRAME_RECORDING_FAILED = "call.frame_recording_failed"
EVENT_TYPE_CALL_FRAME_RECORDING_READY = "call.frame_recording_ready"
EVENT_TYPE_CALL_FRAME_RECORDING_STARTED = "call.frame_recording_started"
EVENT_TYPE_CALL_FRAME_RECORDING_STOPPED = "call.frame_recording_stopped"
EVENT_TYPE_CALL_HLS_BROADCASTING_FAILED = "call.hls_broadcasting_failed"
EVENT_TYPE_CALL_HLS_BROADCASTING_STARTED = "call.hls_broadcasting_started"
EVENT_TYPE_CALL_HLS_BROADCASTING_STOPPED = "call.hls_broadcasting_stopped"
EVENT_TYPE_CALL_KICKED_USER = "call.kicked_user"
EVENT_TYPE_CALL_LIVE_STARTED = "call.live_started"
EVENT_TYPE_CALL_MEMBER_ADDED = "call.member_added"
EVENT_TYPE_CALL_MEMBER_REMOVED = "call.member_removed"
EVENT_TYPE_CALL_MEMBER_UPDATED = "call.member_updated"
EVENT_TYPE_CALL_MEMBER_UPDATED_PERMISSION = "call.member_updated_permission"
EVENT_TYPE_CALL_MISSED = "call.missed"
EVENT_TYPE_CALL_MODERATION_BLUR = "call.moderation_blur"
EVENT_TYPE_CALL_MODERATION_WARNING = "call.moderation_warning"
EVENT_TYPE_CALL_NOTIFICATION = "call.notification"
EVENT_TYPE_CALL_PERMISSION_REQUEST = "call.permission_request"
EVENT_TYPE_CALL_PERMISSIONS_UPDATED = "call.permissions_updated"
EVENT_TYPE_CALL_REACTION_NEW = "call.reaction_new"
EVENT_TYPE_CALL_RECORDING_FAILED = "call.recording_failed"
EVENT_TYPE_CALL_RECORDING_READY = "call.recording_ready"
EVENT_TYPE_CALL_RECORDING_STARTED = "call.recording_started"
EVENT_TYPE_CALL_RECORDING_STOPPED = "call.recording_stopped"
EVENT_TYPE_CALL_REJECTED = "call.rejected"
EVENT_TYPE_CALL_RING = "call.ring"
EVENT_TYPE_CALL_RTMP_BROADCAST_FAILED = "call.rtmp_broadcast_failed"
EVENT_TYPE_CALL_RTMP_BROADCAST_STARTED = "call.rtmp_broadcast_started"
EVENT_TYPE_CALL_RTMP_BROADCAST_STOPPED = "call.rtmp_broadcast_stopped"
EVENT_TYPE_CALL_SESSION_ENDED = "call.session_ended"
EVENT_TYPE_CALL_SESSION_PARTICIPANT_COUNT_UPDATED = (
    "call.session_participant_count_updated"
)
EVENT_TYPE_CALL_SESSION_PARTICIPANT_JOINED = "call.session_participant_joined"
EVENT_TYPE_CALL_SESSION_PARTICIPANT_LEFT = "call.session_participant_left"
EVENT_TYPE_CALL_SESSION_STARTED = "call.session_started"
EVENT_TYPE_CALL_STATS_REPORT_READY = "call.stats_report_ready"
EVENT_TYPE_CALL_TRANSCRIPTION_FAILED = "call.transcription_failed"
EVENT_TYPE_CALL_TRANSCRIPTION_READY = "call.transcription_ready"
EVENT_TYPE_CALL_TRANSCRIPTION_STARTED = "call.transcription_started"
EVENT_TYPE_CALL_TRANSCRIPTION_STOPPED = "call.transcription_stopped"
EVENT_TYPE_CALL_UNBLOCKED_USER = "call.unblocked_user"
EVENT_TYPE_CALL_UPDATED = "call.updated"
EVENT_TYPE_CALL_USER_FEEDBACK_SUBMITTED = "call.user_feedback_submitted"
EVENT_TYPE_CALL_USER_MUTED = "call.user_muted"
EVENT_TYPE_CAMPAIGN_COMPLETED = "campaign.completed"
EVENT_TYPE_CAMPAIGN_STARTED = "campaign.started"
EVENT_TYPE_CHANNEL_CREATED = "channel.created"
EVENT_TYPE_CHANNEL_DELETED = "channel.deleted"
EVENT_TYPE_CHANNEL_FROZEN = "channel.frozen"
EVENT_TYPE_CHANNEL_HIDDEN = "channel.hidden"
EVENT_TYPE_CHANNEL_MAX_STREAK_CHANGED = "channel.max_streak_changed"
EVENT_TYPE_CHANNEL_MUTED = "channel.muted"
EVENT_TYPE_CHANNEL_TRUNCATED = "channel.truncated"
EVENT_TYPE_CHANNEL_UNFROZEN = "channel.unfrozen"
EVENT_TYPE_CHANNEL_UNMUTED = "channel.unmuted"
EVENT_TYPE_CHANNEL_UPDATED = "channel.updated"
EVENT_TYPE_CHANNEL_VISIBLE = "channel.visible"
EVENT_TYPE_CHANNEL_BATCH_UPDATE_COMPLETED = "channel_batch_update.completed"
EVENT_TYPE_CHANNEL_BATCH_UPDATE_STARTED = "channel_batch_update.started"
EVENT_TYPE_CUSTOM = "custom"
EVENT_TYPE_EXPORT_BULK_IMAGE_MODERATION_ERROR = "export.bulk_image_moderation.error"
EVENT_TYPE_EXPORT_BULK_IMAGE_MODERATION_SUCCESS = "export.bulk_image_moderation.success"
EVENT_TYPE_EXPORT_CHANNELS_ERROR = "export.channels.error"
EVENT_TYPE_EXPORT_CHANNELS_SUCCESS = "export.channels.success"
EVENT_TYPE_EXPORT_MODERATION_LOGS_ERROR = "export.moderation_logs.error"
EVENT_TYPE_EXPORT_MODERATION_LOGS_SUCCESS = "export.moderation_logs.success"
EVENT_TYPE_EXPORT_USERS_ERROR = "export.users.error"
EVENT_TYPE_EXPORT_USERS_SUCCESS = "export.users.success"
EVENT_TYPE_FEEDS_ACTIVITY_ADDED = "feeds.activity.added"
EVENT_TYPE_FEEDS_ACTIVITY_DELETED = "feeds.activity.deleted"
EVENT_TYPE_FEEDS_ACTIVITY_FEEDBACK = "feeds.activity.feedback"
EVENT_TYPE_FEEDS_ACTIVITY_MARKED = "feeds.activity.marked"
EVENT_TYPE_FEEDS_ACTIVITY_PINNED = "feeds.activity.pinned"
EVENT_TYPE_FEEDS_ACTIVITY_REACTION_ADDED = "feeds.activity.reaction.added"
EVENT_TYPE_FEEDS_ACTIVITY_REACTION_DELETED = "feeds.activity.reaction.deleted"
EVENT_TYPE_FEEDS_ACTIVITY_REACTION_UPDATED = "feeds.activity.reaction.updated"
EVENT_TYPE_FEEDS_ACTIVITY_REMOVED_FROM_FEED = "feeds.activity.removed_from_feed"
EVENT_TYPE_FEEDS_ACTIVITY_UNPINNED = "feeds.activity.unpinned"
EVENT_TYPE_FEEDS_ACTIVITY_UPDATED = "feeds.activity.updated"
EVENT_TYPE_FEEDS_BOOKMARK_ADDED = "feeds.bookmark.added"
EVENT_TYPE_FEEDS_BOOKMARK_DELETED = "feeds.bookmark.deleted"
EVENT_TYPE_FEEDS_BOOKMARK_UPDATED = "feeds.bookmark.updated"
EVENT_TYPE_FEEDS_BOOKMARK_FOLDER_DELETED = "feeds.bookmark_folder.deleted"
EVENT_TYPE_FEEDS_BOOKMARK_FOLDER_UPDATED = "feeds.bookmark_folder.updated"
EVENT_TYPE_FEEDS_COMMENT_ADDED = "feeds.comment.added"
EVENT_TYPE_FEEDS_COMMENT_DELETED = "feeds.comment.deleted"
EVENT_TYPE_FEEDS_COMMENT_REACTION_ADDED = "feeds.comment.reaction.added"
EVENT_TYPE_FEEDS_COMMENT_REACTION_DELETED = "feeds.comment.reaction.deleted"
EVENT_TYPE_FEEDS_COMMENT_REACTION_UPDATED = "feeds.comment.reaction.updated"
EVENT_TYPE_FEEDS_COMMENT_UPDATED = "feeds.comment.updated"
EVENT_TYPE_FEEDS_FEED_CREATED = "feeds.feed.created"
EVENT_TYPE_FEEDS_FEED_DELETED = "feeds.feed.deleted"
EVENT_TYPE_FEEDS_FEED_UPDATED = "feeds.feed.updated"
EVENT_TYPE_FEEDS_FEED_GROUP_CHANGED = "feeds.feed_group.changed"
EVENT_TYPE_FEEDS_FEED_GROUP_DELETED = "feeds.feed_group.deleted"
EVENT_TYPE_FEEDS_FEED_MEMBER_ADDED = "feeds.feed_member.added"
EVENT_TYPE_FEEDS_FEED_MEMBER_REMOVED = "feeds.feed_member.removed"
EVENT_TYPE_FEEDS_FEED_MEMBER_UPDATED = "feeds.feed_member.updated"
EVENT_TYPE_FEEDS_FOLLOW_CREATED = "feeds.follow.created"
EVENT_TYPE_FEEDS_FOLLOW_DELETED = "feeds.follow.deleted"
EVENT_TYPE_FEEDS_FOLLOW_UPDATED = "feeds.follow.updated"
EVENT_TYPE_FEEDS_NOTIFICATION_FEED_UPDATED = "feeds.notification_feed.updated"
EVENT_TYPE_FEEDS_STORIES_FEED_UPDATED = "feeds.stories_feed.updated"
EVENT_TYPE_FLAG_UPDATED = "flag.updated"
EVENT_TYPE_MEMBER_ADDED = "member.added"
EVENT_TYPE_MEMBER_REMOVED = "member.removed"
EVENT_TYPE_MEMBER_UPDATED = "member.updated"
EVENT_TYPE_MESSAGE_DELETED = "message.deleted"
EVENT_TYPE_MESSAGE_FLAGGED = "message.flagged"
EVENT_TYPE_MESSAGE_NEW = "message.new"
EVENT_TYPE_MESSAGE_PENDING = "message.pending"
EVENT_TYPE_MESSAGE_READ = "message.read"
EVENT_TYPE_MESSAGE_UNBLOCKED = "message.unblocked"
EVENT_TYPE_MESSAGE_UNDELETED = "message.undeleted"
EVENT_TYPE_MESSAGE_UPDATED = "message.updated"
EVENT_TYPE_MODERATION_CUSTOM_ACTION = "moderation.custom_action"
EVENT_TYPE_MODERATION_FLAGGED = "moderation.flagged"
EVENT_TYPE_MODERATION_MARK_REVIEWED = "moderation.mark_reviewed"
EVENT_TYPE_MODERATION_CHECK_COMPLETED = "moderation_check.completed"
EVENT_TYPE_NOTIFICATION_MARK_UNREAD = "notification.mark_unread"
EVENT_TYPE_NOTIFICATION_REMINDER_DUE = "notification.reminder_due"
EVENT_TYPE_NOTIFICATION_THREAD_MESSAGE_NEW = "notification.thread_message_new"
EVENT_TYPE_REACTION_DELETED = "reaction.deleted"
EVENT_TYPE_REACTION_NEW = "reaction.new"
EVENT_TYPE_REACTION_UPDATED = "reaction.updated"
EVENT_TYPE_REMINDER_CREATED = "reminder.created"
EVENT_TYPE_REMINDER_DELETED = "reminder.deleted"
EVENT_TYPE_REMINDER_UPDATED = "reminder.updated"
EVENT_TYPE_REVIEW_QUEUE_ITEM_NEW = "review_queue_item.new"
EVENT_TYPE_REVIEW_QUEUE_ITEM_UPDATED = "review_queue_item.updated"
EVENT_TYPE_THREAD_UPDATED = "thread.updated"
EVENT_TYPE_USER_BANNED = "user.banned"
EVENT_TYPE_USER_DEACTIVATED = "user.deactivated"
EVENT_TYPE_USER_DELETED = "user.deleted"
EVENT_TYPE_USER_FLAGGED = "user.flagged"
EVENT_TYPE_USER_MESSAGES_DELETED = "user.messages.deleted"
EVENT_TYPE_USER_MUTED = "user.muted"
EVENT_TYPE_USER_REACTIVATED = "user.reactivated"
EVENT_TYPE_USER_UNBANNED = "user.unbanned"
EVENT_TYPE_USER_UNMUTED = "user.unmuted"
EVENT_TYPE_USER_UNREAD_MESSAGE_REMINDER = "user.unread_message_reminder"
EVENT_TYPE_USER_UPDATED = "user.updated"


def get_event_type(raw_event: Union[bytes, str, Dict[str, Any]]) -> str:
    """
    Extract the event type from a raw webhook payload.

    Args:
        raw_event: The raw webhook payload

    Returns:
        The event type string (e.g., "message.new"), or empty string if parsing fails
    """
    if isinstance(raw_event, dict):
        return raw_event.get("type", "")

    try:
        if isinstance(raw_event, bytes):
            raw_event = raw_event.decode("utf-8")
        data = json.loads(raw_event)
        return data.get("type", "")
    except (json.JSONDecodeError, UnicodeDecodeError, AttributeError):
        return ""


def parse_webhook_event(raw_event: Union[bytes, str, Dict[str, Any]]) -> Any:
    """
    Deserialize a raw webhook payload into a typed event object.

    Args:
        raw_event: The raw webhook payload

    Returns:
        A typed event object corresponding to the event type

    Raises:
        ValueError: If the event type is unknown or deserialization fails
    """
    try:
        if isinstance(raw_event, dict):
            data = raw_event
        elif isinstance(raw_event, bytes):
            data = json.loads(raw_event.decode("utf-8"))
        else:
            data = json.loads(raw_event)
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        raise ValueError(f"Failed to parse webhook payload: {e}")

    event_type = data.get("type")
    if not event_type:
        raise ValueError("Webhook payload missing 'type' field")

    event_class = _get_event_class(event_type)
    if event_class is None:
        raise ValueError(f"Unknown webhook event type: {event_type}")

    return event_class(**data)


def _get_event_class(event_type: str):
    """Map event type to event class."""
    event_map = {
        "*": CustomEvent,
        "appeal.accepted": AppealAcceptedEvent,
        "appeal.created": AppealCreatedEvent,
        "appeal.rejected": AppealRejectedEvent,
        "call.accepted": CallAcceptedEvent,
        "call.blocked_user": BlockedUserEvent,
        "call.closed_caption": ClosedCaptionEvent,
        "call.closed_captions_failed": CallClosedCaptionsFailedEvent,
        "call.closed_captions_started": CallClosedCaptionsStartedEvent,
        "call.closed_captions_stopped": CallClosedCaptionsStoppedEvent,
        "call.created": CallCreatedEvent,
        "call.deleted": CallDeletedEvent,
        "call.ended": CallEndedEvent,
        "call.frame_recording_failed": CallFrameRecordingFailedEvent,
        "call.frame_recording_ready": CallFrameRecordingFrameReadyEvent,
        "call.frame_recording_started": CallFrameRecordingStartedEvent,
        "call.frame_recording_stopped": CallFrameRecordingStoppedEvent,
        "call.hls_broadcasting_failed": CallHLSBroadcastingFailedEvent,
        "call.hls_broadcasting_started": CallHLSBroadcastingStartedEvent,
        "call.hls_broadcasting_stopped": CallHLSBroadcastingStoppedEvent,
        "call.kicked_user": KickedUserEvent,
        "call.live_started": CallLiveStartedEvent,
        "call.member_added": CallMemberAddedEvent,
        "call.member_removed": CallMemberRemovedEvent,
        "call.member_updated": CallMemberUpdatedEvent,
        "call.member_updated_permission": CallMemberUpdatedPermissionEvent,
        "call.missed": CallMissedEvent,
        "call.moderation_blur": CallModerationBlurEvent,
        "call.moderation_warning": CallModerationWarningEvent,
        "call.notification": CallNotificationEvent,
        "call.permission_request": PermissionRequestEvent,
        "call.permissions_updated": UpdatedCallPermissionsEvent,
        "call.reaction_new": CallReactionEvent,
        "call.recording_failed": CallRecordingFailedEvent,
        "call.recording_ready": CallRecordingReadyEvent,
        "call.recording_started": CallRecordingStartedEvent,
        "call.recording_stopped": CallRecordingStoppedEvent,
        "call.rejected": CallRejectedEvent,
        "call.ring": CallRingEvent,
        "call.rtmp_broadcast_failed": CallRtmpBroadcastFailedEvent,
        "call.rtmp_broadcast_started": CallRtmpBroadcastStartedEvent,
        "call.rtmp_broadcast_stopped": CallRtmpBroadcastStoppedEvent,
        "call.session_ended": CallSessionEndedEvent,
        "call.session_participant_count_updated": CallSessionParticipantCountsUpdatedEvent,
        "call.session_participant_joined": CallSessionParticipantJoinedEvent,
        "call.session_participant_left": CallSessionParticipantLeftEvent,
        "call.session_started": CallSessionStartedEvent,
        "call.stats_report_ready": CallStatsReportReadyEvent,
        "call.transcription_failed": CallTranscriptionFailedEvent,
        "call.transcription_ready": CallTranscriptionReadyEvent,
        "call.transcription_started": CallTranscriptionStartedEvent,
        "call.transcription_stopped": CallTranscriptionStoppedEvent,
        "call.unblocked_user": UnblockedUserEvent,
        "call.updated": CallUpdatedEvent,
        "call.user_feedback_submitted": CallUserFeedbackSubmittedEvent,
        "call.user_muted": CallUserMutedEvent,
        "campaign.completed": CampaignCompletedEvent,
        "campaign.started": CampaignStartedEvent,
        "channel.created": ChannelCreatedEvent,
        "channel.deleted": ChannelDeletedEvent,
        "channel.frozen": ChannelFrozenEvent,
        "channel.hidden": ChannelHiddenEvent,
        "channel.max_streak_changed": MaxStreakChangedEvent,
        "channel.muted": ChannelMutedEvent,
        "channel.truncated": ChannelTruncatedEvent,
        "channel.unfrozen": ChannelUnFrozenEvent,
        "channel.unmuted": ChannelUnmutedEvent,
        "channel.updated": ChannelUpdatedEvent,
        "channel.visible": ChannelVisibleEvent,
        "channel_batch_update.completed": ChannelBatchCompletedEvent,
        "channel_batch_update.started": ChannelBatchStartedEvent,
        "custom": CustomVideoEvent,
        "export.bulk_image_moderation.error": AsyncExportErrorEvent,
        "export.bulk_image_moderation.success": AsyncBulkImageModerationEvent,
        "export.channels.error": AsyncExportErrorEvent,
        "export.channels.success": AsyncExportChannelsEvent,
        "export.moderation_logs.error": AsyncExportErrorEvent,
        "export.moderation_logs.success": AsyncExportModerationLogsEvent,
        "export.users.error": AsyncExportErrorEvent,
        "export.users.success": AsyncExportUsersEvent,
        "feeds.activity.added": ActivityAddedEvent,
        "feeds.activity.deleted": ActivityDeletedEvent,
        "feeds.activity.feedback": ActivityFeedbackEvent,
        "feeds.activity.marked": ActivityMarkEvent,
        "feeds.activity.pinned": ActivityPinnedEvent,
        "feeds.activity.reaction.added": ActivityReactionAddedEvent,
        "feeds.activity.reaction.deleted": ActivityReactionDeletedEvent,
        "feeds.activity.reaction.updated": ActivityReactionUpdatedEvent,
        "feeds.activity.removed_from_feed": ActivityRemovedFromFeedEvent,
        "feeds.activity.unpinned": ActivityUnpinnedEvent,
        "feeds.activity.updated": ActivityUpdatedEvent,
        "feeds.bookmark.added": BookmarkAddedEvent,
        "feeds.bookmark.deleted": BookmarkDeletedEvent,
        "feeds.bookmark.updated": BookmarkUpdatedEvent,
        "feeds.bookmark_folder.deleted": BookmarkFolderDeletedEvent,
        "feeds.bookmark_folder.updated": BookmarkFolderUpdatedEvent,
        "feeds.comment.added": CommentAddedEvent,
        "feeds.comment.deleted": CommentDeletedEvent,
        "feeds.comment.reaction.added": CommentReactionAddedEvent,
        "feeds.comment.reaction.deleted": CommentReactionDeletedEvent,
        "feeds.comment.reaction.updated": CommentReactionUpdatedEvent,
        "feeds.comment.updated": CommentUpdatedEvent,
        "feeds.feed.created": FeedCreatedEvent,
        "feeds.feed.deleted": FeedDeletedEvent,
        "feeds.feed.updated": FeedUpdatedEvent,
        "feeds.feed_group.changed": FeedGroupChangedEvent,
        "feeds.feed_group.deleted": FeedGroupDeletedEvent,
        "feeds.feed_member.added": FeedMemberAddedEvent,
        "feeds.feed_member.removed": FeedMemberRemovedEvent,
        "feeds.feed_member.updated": FeedMemberUpdatedEvent,
        "feeds.follow.created": FollowCreatedEvent,
        "feeds.follow.deleted": FollowDeletedEvent,
        "feeds.follow.updated": FollowUpdatedEvent,
        "feeds.notification_feed.updated": NotificationFeedUpdatedEvent,
        "feeds.stories_feed.updated": StoriesFeedUpdatedEvent,
        "flag.updated": FlagUpdatedEvent,
        "member.added": MemberAddedEvent,
        "member.removed": MemberRemovedEvent,
        "member.updated": MemberUpdatedEvent,
        "message.deleted": MessageDeletedEvent,
        "message.flagged": MessageFlaggedEvent,
        "message.new": MessageNewEvent,
        "message.pending": PendingMessageEvent,
        "message.read": MessageReadEvent,
        "message.unblocked": MessageUnblockedEvent,
        "message.undeleted": MessageUndeletedEvent,
        "message.updated": MessageUpdatedEvent,
        "moderation.custom_action": ModerationCustomActionEvent,
        "moderation.flagged": ModerationFlaggedEvent,
        "moderation.mark_reviewed": ModerationMarkReviewedEvent,
        "moderation_check.completed": ModerationCheckCompletedEvent,
        "notification.mark_unread": NotificationMarkUnreadEvent,
        "notification.reminder_due": ReminderNotificationEvent,
        "notification.thread_message_new": NotificationThreadMessageNewEvent,
        "reaction.deleted": ReactionDeletedEvent,
        "reaction.new": ReactionNewEvent,
        "reaction.updated": ReactionUpdatedEvent,
        "reminder.created": ReminderCreatedEvent,
        "reminder.deleted": ReminderDeletedEvent,
        "reminder.updated": ReminderUpdatedEvent,
        "review_queue_item.new": ReviewQueueItemNewEvent,
        "review_queue_item.updated": ReviewQueueItemUpdatedEvent,
        "thread.updated": ThreadUpdatedEvent,
        "user.banned": UserBannedEvent,
        "user.deactivated": UserDeactivatedEvent,
        "user.deleted": UserDeletedEvent,
        "user.flagged": UserFlaggedEvent,
        "user.messages.deleted": UserMessagesDeletedEvent,
        "user.muted": UserMutedEvent,
        "user.reactivated": UserReactivatedEvent,
        "user.unbanned": UserUnbannedEvent,
        "user.unmuted": UserUnmutedEvent,
        "user.unread_message_reminder": UserUnreadReminderEvent,
        "user.updated": UserUpdatedEvent,
    }
    return event_map.get(event_type)


def verify_webhook_signature(
    body: Union[bytes, str], signature: str, secret: str
) -> bool:
    """
    Verify the HMAC-SHA256 signature of a webhook payload.

    Args:
        body: The raw request body (bytes or UTF-8 string)
        signature: The signature from the X-Signature header
        secret: Your webhook secret (found in the Stream Dashboard)

    Returns:
        True if the signature is valid, False otherwise
    """
    if isinstance(body, str):
        body = body.encode("utf-8")

    h = hmac.new(secret.encode("utf-8"), body, hashlib.sha256)
    expected = h.hexdigest()
    return hmac.compare_digest(signature, expected)
