[project]
name = "record-audio"
version = "0.1.0"
description = "Recording Audio with Stream"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "getstream[webrtc]>=2.3.0a0",
    "python-dotenv>=1.1.1",
    "aiortc",
    "numpy",
]

[project.scripts]
record-audio = "main:main"
