"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import video.sfu.models.models_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class StartNoiseCancellationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["session_id", b"session_id"]
    ) -> None: ...

global___StartNoiseCancellationRequest = StartNoiseCancellationRequest

@typing_extensions.final
class StartNoiseCancellationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> video.sfu.models.models_pb2.Error: ...
    def __init__(
        self,
        *,
        error: video.sfu.models.models_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> None: ...

global___StartNoiseCancellationResponse = StartNoiseCancellationResponse

@typing_extensions.final
class StopNoiseCancellationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["session_id", b"session_id"]
    ) -> None: ...

global___StopNoiseCancellationRequest = StopNoiseCancellationRequest

@typing_extensions.final
class StopNoiseCancellationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> video.sfu.models.models_pb2.Error: ...
    def __init__(
        self,
        *,
        error: video.sfu.models.models_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> None: ...

global___StopNoiseCancellationResponse = StopNoiseCancellationResponse

@typing_extensions.final
class Reconnection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIME_SECONDS_FIELD_NUMBER: builtins.int
    STRATEGY_FIELD_NUMBER: builtins.int
    time_seconds: builtins.float
    strategy: video.sfu.models.models_pb2.WebsocketReconnectStrategy.ValueType
    def __init__(
        self,
        *,
        time_seconds: builtins.float = ...,
        strategy: video.sfu.models.models_pb2.WebsocketReconnectStrategy.ValueType = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "strategy", b"strategy", "time_seconds", b"time_seconds"
        ],
    ) -> None: ...

global___Reconnection = Reconnection

@typing_extensions.final
class Telemetry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTION_TIME_SECONDS_FIELD_NUMBER: builtins.int
    RECONNECTION_FIELD_NUMBER: builtins.int
    connection_time_seconds: builtins.float
    @property
    def reconnection(self) -> global___Reconnection: ...
    def __init__(
        self,
        *,
        connection_time_seconds: builtins.float = ...,
        reconnection: global___Reconnection | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "connection_time_seconds",
            b"connection_time_seconds",
            "data",
            b"data",
            "reconnection",
            b"reconnection",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "connection_time_seconds",
            b"connection_time_seconds",
            "data",
            b"data",
            "reconnection",
            b"reconnection",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions.Literal["data", b"data"]
    ) -> (
        typing_extensions.Literal["connection_time_seconds", "reconnection"] | None
    ): ...

global___Telemetry = Telemetry

@typing_extensions.final
class SendStatsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    SUBSCRIBER_STATS_FIELD_NUMBER: builtins.int
    PUBLISHER_STATS_FIELD_NUMBER: builtins.int
    WEBRTC_VERSION_FIELD_NUMBER: builtins.int
    SDK_FIELD_NUMBER: builtins.int
    SDK_VERSION_FIELD_NUMBER: builtins.int
    AUDIO_DEVICES_FIELD_NUMBER: builtins.int
    VIDEO_DEVICES_FIELD_NUMBER: builtins.int
    ANDROID_FIELD_NUMBER: builtins.int
    APPLE_FIELD_NUMBER: builtins.int
    TELEMETRY_FIELD_NUMBER: builtins.int
    RTMP_FIELD_NUMBER: builtins.int
    SUBSCRIBER_RTC_STATS_FIELD_NUMBER: builtins.int
    PUBLISHER_RTC_STATS_FIELD_NUMBER: builtins.int
    RTC_STATS_FIELD_NUMBER: builtins.int
    ENCODE_STATS_FIELD_NUMBER: builtins.int
    DECODE_STATS_FIELD_NUMBER: builtins.int
    UNIFIED_SESSION_ID_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    subscriber_stats: builtins.str
    publisher_stats: builtins.str
    webrtc_version: builtins.str
    sdk: builtins.str
    sdk_version: builtins.str
    @property
    def audio_devices(self) -> video.sfu.models.models_pb2.InputDevices: ...
    @property
    def video_devices(self) -> video.sfu.models.models_pb2.InputDevices: ...
    @property
    def android(self) -> video.sfu.models.models_pb2.AndroidState: ...
    @property
    def apple(self) -> video.sfu.models.models_pb2.AppleState: ...
    @property
    def telemetry(self) -> global___Telemetry: ...
    @property
    def rtmp(self) -> video.sfu.models.models_pb2.RTMPIngress: ...
    subscriber_rtc_stats: builtins.str
    publisher_rtc_stats: builtins.str
    rtc_stats: builtins.str
    @property
    def encode_stats(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        video.sfu.models.models_pb2.PerformanceStats
    ]:
        """Encode stats for the publisher"""
    @property
    def decode_stats(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        video.sfu.models.models_pb2.PerformanceStats
    ]:
        """Decode stats for the subscriber"""
    unified_session_id: builtins.str
    """user_session id can change during reconnects, this helps us to
    identify the user across reconnects and should remain consistent until the user explicitly
    disconnects, is kicked or the call is ended.
    """
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        subscriber_stats: builtins.str = ...,
        publisher_stats: builtins.str = ...,
        webrtc_version: builtins.str = ...,
        sdk: builtins.str = ...,
        sdk_version: builtins.str = ...,
        audio_devices: video.sfu.models.models_pb2.InputDevices | None = ...,
        video_devices: video.sfu.models.models_pb2.InputDevices | None = ...,
        android: video.sfu.models.models_pb2.AndroidState | None = ...,
        apple: video.sfu.models.models_pb2.AppleState | None = ...,
        telemetry: global___Telemetry | None = ...,
        rtmp: video.sfu.models.models_pb2.RTMPIngress | None = ...,
        subscriber_rtc_stats: builtins.str = ...,
        publisher_rtc_stats: builtins.str = ...,
        rtc_stats: builtins.str = ...,
        encode_stats: collections.abc.Iterable[
            video.sfu.models.models_pb2.PerformanceStats
        ]
        | None = ...,
        decode_stats: collections.abc.Iterable[
            video.sfu.models.models_pb2.PerformanceStats
        ]
        | None = ...,
        unified_session_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "android",
            b"android",
            "apple",
            b"apple",
            "audio_devices",
            b"audio_devices",
            "device_state",
            b"device_state",
            "rtmp",
            b"rtmp",
            "telemetry",
            b"telemetry",
            "video_devices",
            b"video_devices",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "android",
            b"android",
            "apple",
            b"apple",
            "audio_devices",
            b"audio_devices",
            "decode_stats",
            b"decode_stats",
            "device_state",
            b"device_state",
            "encode_stats",
            b"encode_stats",
            "publisher_rtc_stats",
            b"publisher_rtc_stats",
            "publisher_stats",
            b"publisher_stats",
            "rtc_stats",
            b"rtc_stats",
            "rtmp",
            b"rtmp",
            "sdk",
            b"sdk",
            "sdk_version",
            b"sdk_version",
            "session_id",
            b"session_id",
            "subscriber_rtc_stats",
            b"subscriber_rtc_stats",
            "subscriber_stats",
            b"subscriber_stats",
            "telemetry",
            b"telemetry",
            "unified_session_id",
            b"unified_session_id",
            "video_devices",
            b"video_devices",
            "webrtc_version",
            b"webrtc_version",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions.Literal["device_state", b"device_state"]
    ) -> typing_extensions.Literal["android", "apple"] | None: ...

global___SendStatsRequest = SendStatsRequest

@typing_extensions.final
class SendStatsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> video.sfu.models.models_pb2.Error: ...
    def __init__(
        self,
        *,
        error: video.sfu.models.models_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> None: ...

global___SendStatsResponse = SendStatsResponse

@typing_extensions.final
class ICERestartRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    PEER_TYPE_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    peer_type: video.sfu.models.models_pb2.PeerType.ValueType
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        peer_type: video.sfu.models.models_pb2.PeerType.ValueType = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "peer_type", b"peer_type", "session_id", b"session_id"
        ],
    ) -> None: ...

global___ICERestartRequest = ICERestartRequest

@typing_extensions.final
class ICERestartResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> video.sfu.models.models_pb2.Error: ...
    def __init__(
        self,
        *,
        error: video.sfu.models.models_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> None: ...

global___ICERestartResponse = ICERestartResponse

@typing_extensions.final
class UpdateMuteStatesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    MUTE_STATES_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    @property
    def mute_states(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___TrackMuteState
    ]: ...
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        mute_states: collections.abc.Iterable[global___TrackMuteState] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "mute_states", b"mute_states", "session_id", b"session_id"
        ],
    ) -> None: ...

global___UpdateMuteStatesRequest = UpdateMuteStatesRequest

@typing_extensions.final
class UpdateMuteStatesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> video.sfu.models.models_pb2.Error: ...
    def __init__(
        self,
        *,
        error: video.sfu.models.models_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> None: ...

global___UpdateMuteStatesResponse = UpdateMuteStatesResponse

@typing_extensions.final
class TrackMuteState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRACK_TYPE_FIELD_NUMBER: builtins.int
    MUTED_FIELD_NUMBER: builtins.int
    track_type: video.sfu.models.models_pb2.TrackType.ValueType
    muted: builtins.bool
    def __init__(
        self,
        *,
        track_type: video.sfu.models.models_pb2.TrackType.ValueType = ...,
        muted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "muted", b"muted", "track_type", b"track_type"
        ],
    ) -> None: ...

global___TrackMuteState = TrackMuteState

@typing_extensions.final
class AudioMuteChanged(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MUTED_FIELD_NUMBER: builtins.int
    muted: builtins.bool
    def __init__(
        self,
        *,
        muted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["muted", b"muted"]
    ) -> None: ...

global___AudioMuteChanged = AudioMuteChanged

@typing_extensions.final
class VideoMuteChanged(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MUTED_FIELD_NUMBER: builtins.int
    muted: builtins.bool
    def __init__(
        self,
        *,
        muted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["muted", b"muted"]
    ) -> None: ...

global___VideoMuteChanged = VideoMuteChanged

@typing_extensions.final
class UpdateSubscriptionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    TRACKS_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    @property
    def tracks(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___TrackSubscriptionDetails
    ]: ...
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        tracks: collections.abc.Iterable[global___TrackSubscriptionDetails]
        | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "session_id", b"session_id", "tracks", b"tracks"
        ],
    ) -> None: ...

global___UpdateSubscriptionsRequest = UpdateSubscriptionsRequest

@typing_extensions.final
class UpdateSubscriptionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> video.sfu.models.models_pb2.Error: ...
    def __init__(
        self,
        *,
        error: video.sfu.models.models_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> None: ...

global___UpdateSubscriptionsResponse = UpdateSubscriptionsResponse

@typing_extensions.final
class TrackSubscriptionDetails(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    TRACK_TYPE_FIELD_NUMBER: builtins.int
    DIMENSION_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    session_id: builtins.str
    track_type: video.sfu.models.models_pb2.TrackType.ValueType
    @property
    def dimension(self) -> video.sfu.models.models_pb2.VideoDimension: ...
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        session_id: builtins.str = ...,
        track_type: video.sfu.models.models_pb2.TrackType.ValueType = ...,
        dimension: video.sfu.models.models_pb2.VideoDimension | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["dimension", b"dimension"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "dimension",
            b"dimension",
            "session_id",
            b"session_id",
            "track_type",
            b"track_type",
            "user_id",
            b"user_id",
        ],
    ) -> None: ...

global___TrackSubscriptionDetails = TrackSubscriptionDetails

@typing_extensions.final
class SendAnswerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PEER_TYPE_FIELD_NUMBER: builtins.int
    SDP_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    peer_type: video.sfu.models.models_pb2.PeerType.ValueType
    sdp: builtins.str
    session_id: builtins.str
    def __init__(
        self,
        *,
        peer_type: video.sfu.models.models_pb2.PeerType.ValueType = ...,
        sdp: builtins.str = ...,
        session_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "peer_type", b"peer_type", "sdp", b"sdp", "session_id", b"session_id"
        ],
    ) -> None: ...

global___SendAnswerRequest = SendAnswerRequest

@typing_extensions.final
class SendAnswerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> video.sfu.models.models_pb2.Error: ...
    def __init__(
        self,
        *,
        error: video.sfu.models.models_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> None: ...

global___SendAnswerResponse = SendAnswerResponse

@typing_extensions.final
class ICETrickleResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> video.sfu.models.models_pb2.Error: ...
    def __init__(
        self,
        *,
        error: video.sfu.models.models_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> None: ...

global___ICETrickleResponse = ICETrickleResponse

@typing_extensions.final
class SetPublisherRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SDP_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    TRACKS_FIELD_NUMBER: builtins.int
    sdp: builtins.str
    """sdp offer"""
    session_id: builtins.str
    @property
    def tracks(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        video.sfu.models.models_pb2.TrackInfo
    ]: ...
    def __init__(
        self,
        *,
        sdp: builtins.str = ...,
        session_id: builtins.str = ...,
        tracks: collections.abc.Iterable[video.sfu.models.models_pb2.TrackInfo]
        | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "sdp", b"sdp", "session_id", b"session_id", "tracks", b"tracks"
        ],
    ) -> None: ...

global___SetPublisherRequest = SetPublisherRequest

@typing_extensions.final
class SetPublisherResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SDP_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    ICE_RESTART_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    sdp: builtins.str
    """sdp answer"""
    session_id: builtins.str
    ice_restart: builtins.bool
    @property
    def error(self) -> video.sfu.models.models_pb2.Error: ...
    def __init__(
        self,
        *,
        sdp: builtins.str = ...,
        session_id: builtins.str = ...,
        ice_restart: builtins.bool = ...,
        error: video.sfu.models.models_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["error", b"error"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "error",
            b"error",
            "ice_restart",
            b"ice_restart",
            "sdp",
            b"sdp",
            "session_id",
            b"session_id",
        ],
    ) -> None: ...

global___SetPublisherResponse = SetPublisherResponse
