# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: events.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class AudioFormat(betterproto.Enum):
    Float32 = 0
    Int32 = 1
    Int16 = 2


class ErrorCode(betterproto.Enum):
    """Error message for handling error events"""

    UNKNOWN_ERROR = 0
    CALL_JOIN_ERROR = 1
    AUTHENTICATION_ERROR = 2
    NETWORK_ERROR = 3
    SERVER_ERROR = 4


@dataclass
class MockAudioConfig(betterproto.Message):
    """Mock configuration for testing"""

    audio_file_path: str = betterproto.string_field(1)
    realtime_clock: bool = betterproto.bool_field(2)


@dataclass
class MockParticipant(betterproto.Message):
    user_id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    audio: "MockAudioConfig" = betterproto.message_field(3)


@dataclass
class MockConfig(betterproto.Message):
    participants: List["MockParticipant"] = betterproto.message_field(1)


@dataclass
class RTCPacket(betterproto.Message):
    video: "VideoPayload" = betterproto.message_field(1, group="payload")
    audio: "AudioPayload" = betterproto.message_field(2, group="payload")
    data: "DataPayload" = betterproto.message_field(3, group="payload")


@dataclass
class DataPayload(betterproto.Message):
    pass


@dataclass
class VideoPayload(betterproto.Message):
    payload: bytes = betterproto.bytes_field(1)


@dataclass
class AudioPayload(betterproto.Message):
    pcm: "PCMAudioPayload" = betterproto.message_field(1, group="payload")
    ogg: "OggOpusPayload" = betterproto.message_field(2, group="payload")


@dataclass
class PCMAudioPayload(betterproto.Message):
    payload: bytes = betterproto.bytes_field(1)
    format: "AudioFormat" = betterproto.enum_field(2)
    channels: int = betterproto.int32_field(3)
    sample_rate: int = betterproto.int32_field(4)


@dataclass
class OggOpusPayload(betterproto.Message):
    payload: bytes = betterproto.bytes_field(1)


@dataclass
class ParticipantJoined(betterproto.Message):
    user_id: str = betterproto.string_field(1)


@dataclass
class ParticipantLeft(betterproto.Message):
    user_id: str = betterproto.string_field(1)


@dataclass
class CallEnded(betterproto.Message):
    """Message sent when a call has ended"""

    pass


@dataclass
class Error(betterproto.Message):
    code: "ErrorCode" = betterproto.enum_field(1)
    message: str = betterproto.string_field(2)


@dataclass
class CallJoinResponse(betterproto.Message):
    """Response message for successful call join"""

    pass


@dataclass
class Event(betterproto.Message):
    rtc_packet: "RTCPacket" = betterproto.message_field(1, group="event")
    participant_joined: "ParticipantJoined" = betterproto.message_field(
        2, group="event"
    )
    participant_left: "ParticipantLeft" = betterproto.message_field(3, group="event")
    error: "Error" = betterproto.message_field(4, group="event")
    call_join_response: "CallJoinResponse" = betterproto.message_field(5, group="event")
    call_ended: "CallEnded" = betterproto.message_field(6, group="event")
