name: Create release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The new version number following semantic versioning convention. Example: 1.40.1"
        required: true

jobs:
  init_release:
    name: 🚀 Create release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # gives the changelog generator access to all previous commits

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        run: pipx install poetry

      - name: Get changelog diff
        uses: actions/github-script@v7
        with:
          script: |
            const get_change_log_diff = require('./scripts/get_changelog_diff.js')
            core.exportVariable('CHANGELOG', get_change_log_diff())

      - name: Open pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            -t "Release ${{ github.event.inputs.version }}" \
            -b "# :rocket: ${{ github.event.inputs.version }}
            Make sure to use squash & merge when merging!
            Once this is merged, another job will kick off automatically and publish the package.
            # :memo: Changelog
            ${{ env.CHANGELOG }}"
